System.InvalidOperationException: 'The seed entity for entity type 'User' with the key value 'Id:1' cannot be added because it has the navigation 'Activities' set. To seed relationships you need to add the related entity seed to 'Activity' and specify the foreign key values {'UserId'}.'